title: Rūta Čeidaitė
logo: /assets/profile.jpg
description: Always seeking for new opportunities to discover and express myself, I find a lot of joy in making sense of data and creating logical systems. Lets make data dance!
#show_downloads: true
theme: jekyll-theme-minimal
